split build script and use snippets for ci build

diff --git a/.build_scripts/install_3rd_party b/.build_scripts/install_3rd_party
--- a/.build_scripts/install_3rd_party
+++ b/.build_scripts/install_3rd_party
@@ -1,3 +1,17 @@
 #!/bin/bash
+
+lib=$project_root/.build_scripts/build_lib
+if [[ -f "$lib" ]]; then
+    . "$lib"
+else
+    echo "${build_prefix}unable to source build_lib"
+    exit 1
+fi
+
+#prepare
+section "install external libs"
 cd "$project_root" || exit 1
+#command
 cd external_libs && ./init_libs || exit 1
+#end
+echo
diff --git a/.build_scripts/install_cmake b/.build_scripts/install_cmake
--- a/.build_scripts/install_cmake
+++ b/.build_scripts/install_cmake
@@ -1,4 +1,16 @@
 #!/bin/bash
+
+lib=$project_root/.build_scripts/build_lib
+if [[ -f "$lib" ]]; then
+    . "$lib"
+else
+    echo "${build_prefix}unable to source build_lib"
+    exit 1
+fi
+
+#prepare
+section "install cmake"
+#command
 set -e
 major="3.9"
 minor="5"
@@ -8,3 +20,5 @@ file="cmake-$version-Linux-x86_64.sh"
 wget "https://cmake.org/files/v${major}/${file}"
 chmod +x "$file"
 ./"$file" --prefix="${install_root}" --exclude-subdir --skip-license
+#end
+echo
diff --git a/.build_scripts/system_info b/.build_scripts/system_info
--- a/.build_scripts/system_info
+++ b/.build_scripts/system_info
@@ -1,4 +1,16 @@
 #!/bin/bash
+
+lib=$project_root/.build_scripts/build_lib
+if [[ -f "$lib" ]]; then
+    . "$lib"
+else
+    echo "${build_prefix}unable to source build_lib"
+    exit 1
+fi
+
+#prepare
+section "system info"
+#command
 echo "sources list ##################"
 cat /etc/apt/sources.list
 echo "cpu into ######################"
@@ -6,3 +18,5 @@ cat /proc/cpuinfo
 echo "mem info ######################"
 cat /proc/meminfo
 echo "###############################"
+#end
+echo
diff --git a/.build_scripts/test b/.build_scripts/test
--- a/.build_scripts/test
+++ b/.build_scripts/test
@@ -1,3 +1,17 @@
 #!/bin/bash
-cd $build_root/current || exit 1
-ctest -VV || exit $?
+
+lib=$project_root/.build_scripts/build_lib
+if [[ -f "$lib" ]]; then
+    . "$lib"
+else
+    echo "${build_prefix}unable to source build_lib"
+    exit 1
+fi
+
+#prepare
+section "running tests"
+cd $build_base/current || ferr "unable to change into current build dir"
+#command
+ctest -VV || fserr "running tests - failed" $?
+#end
+echo
diff --git a/.build_scripts/var_info b/.build_scripts/var_info
--- a/.build_scripts/var_info
+++ b/.build_scripts/var_info
@@ -1,7 +1,24 @@
 #!/bin/bash
+
+lib=$project_root/.build_scripts/build_lib
+if [[ -f "$lib" ]]; then
+    . "$lib"
+else
+    echo "${build_prefix}unable to source build_lib"
+    exit 1
+fi
+
+#prepare
+section "variable info"
+#command
+echo "project_root: $project_root"
+echo "build_base:   $build_base"
+echo "build_root:   $build_root"
+echo
+echo "PATH:         $PATH"
 echo "CXX:          $CXX"
 echo "CC:           $CC "
 echo "COMPILER:     $COMPILER"
 echo "IN_TRAVIS:    $IN_TRAVIS"
-echo "project_root: $project_root"
-echo "build_root:   $build_root"
+#end
+echo
